[project]
name = "codec-scan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "rich>=14.0.0",
]

[project.scripts]
codec-scan = "codec_scan:main"

[tool.uv]
package = true
